# Generated by Django 4.2.16 on 2026-03-17 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipapplication',
            name='audit_action',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='audited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='parsed_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='annotations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TeacherChatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(default='prep', max_length=32)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_chat_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
