from django.urls import path

from .views import (
    AdminGraphObservabilityView,
    AdminHypergraphGraphView,
    AdminKnowledgeGraphView,
    AdminOverviewView,
    AdminUserManageView,
    AdminUserStatusUpdateView,
    AgentChatAsyncSubmitView,
    AgentChatTaskStatusView,
    CaseLibrarySummaryView,
    CaseRecallView,
    ChatGuideView,
    CompetitionAdviseAgentView,
    CompetitionCoachChatView,
    CompetitionCoachExportWordView,
    FinancialDesignAgentView,
    HealthView,
    HistoryView,
    HypergraphImportCaseView,
    HypergraphPreviewGraphView,
    LoginView,
    LogicValidateView,
    LogoutView,
    MentorshipApplicationListView,
    MentorshipApplyView,
    MentorshipAuditView,
    MessageListView,
    MessageReadView,
    PlanDeleteView,
    PlanListView,
    PlanReviewListView,
    PlanSubmitToTeacherView,
    PlanUploadView,
    PitchOptimizeAgentView,
    PitchSimulationAgentView,
    ProfileView,
    ProjectBottleneckView,
    ProjectEvidenceChainView,
    ProjectHypergraphReasoningView,
    ProjectPotentialReportView,
    ProjectRubricScoreDetailView,
    PromptSceneConfigListView,
    RegisterView,
    ReviewGenerateAsyncView,
    ReviewGenerateView,
    ReviewTaskStatusView,
    ReviewUpdateView,
    RoadmapSimulateAgentView,
    ScoringRubricListView,
    StudentClassPersonaView,
    StudentPdfChatView,
    StudentPersonaView,
    TeacherAIChatView,
    TeacherAggregateDashboardView,
    TeacherClassLearningReportView,
    TeacherClassPersonaView,
    TeacherClassRadarView,
    TeacherCommonIssuesView,
    TeacherCommonMistakesView,
    TeacherDashboardView,
    TeacherHighRiskProjectsView,
    TeacherInterventionCreateView,
    TeacherKnowledgeRecommendationView,
    TeacherListView,
    TeacherMetricsStreamView,
    TeacherProjectEvidenceDetailView,
    TeacherRuleDrilldownView,
    TeacherStudentListView,
    TeacherStudentUnbindView,
    TutorAgentView,
    WorkflowOrchestrateView,
)

urlpatterns = [
    path("health", HealthView.as_view()),
    path("health/", HealthView.as_view()),
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/profile", ProfileView.as_view()),
    path("history", HistoryView.as_view()),
    path("teachers", TeacherListView.as_view()),
    path("student/persona", StudentPersonaView.as_view()),
    path("student/class-persona", StudentClassPersonaView.as_view()),
    path("ai/chat", ChatGuideView.as_view()),
    path("agent/chat-async", AgentChatAsyncSubmitView.as_view()),
    path("agent/chat-tasks/<int:task_id>", AgentChatTaskStatusView.as_view()),
    path("agent/roadmap-simulate", RoadmapSimulateAgentView.as_view()),
    path("agent/competition-advise", CompetitionAdviseAgentView.as_view()),
    path("agent/competition-coach-chat", CompetitionCoachChatView.as_view()),
    path("agent/competition-coach-export-word", CompetitionCoachExportWordView.as_view()),
    path("agent/financial-design", FinancialDesignAgentView.as_view()),
    path("agent/tutor", TutorAgentView.as_view()),
    path("agent/pitch-optimize", PitchOptimizeAgentView.as_view()),
    path("agent/pitch-simulate", PitchSimulationAgentView.as_view()),
    path("agent/case-recall", CaseRecallView.as_view()),
    path("agent/workflow-orchestrate", WorkflowOrchestrateView.as_view()),
    path("ai/pdf-chat", StudentPdfChatView.as_view()),
    path("ai/validate", LogicValidateView.as_view()),
    path("plans/upload", PlanUploadView.as_view()),
    path("plans", PlanListView.as_view()),
    path("plans/<int:plan_id>", PlanDeleteView.as_view()),
    path("plans/<int:plan_id>/submit", PlanSubmitToTeacherView.as_view()),
    path("plans/<int:plan_id>/reviews", PlanReviewListView.as_view()),
    path("reviews/generate", ReviewGenerateView.as_view()),
    path("reviews/generate-async", ReviewGenerateAsyncView.as_view()),
    path("reviews/tasks/<int:task_id>", ReviewTaskStatusView.as_view()),
    path("reviews/<int:review_id>", ReviewUpdateView.as_view()),
    path("mentorship/apply", MentorshipApplyView.as_view()),
    path("mentorship/applications", MentorshipApplicationListView.as_view()),
    path("mentorship/<int:application_id>/audit", MentorshipAuditView.as_view()),
    path("messages", MessageListView.as_view()),
    path("messages/read", MessageReadView.as_view()),
    path("teacher/dashboard", TeacherDashboardView.as_view()),
    path("teacher/class-radar", TeacherClassRadarView.as_view()),
    path("teacher/class-persona", TeacherClassPersonaView.as_view()),
    path("teacher/aggregate-dashboard", TeacherAggregateDashboardView.as_view()),
    path("teacher/metrics-stream", TeacherMetricsStreamView.as_view()),
    path("teacher/rule-drilldown", TeacherRuleDrilldownView.as_view()),
    path("teacher/project/<int:plan_id>/evidence-detail", TeacherProjectEvidenceDetailView.as_view()),
    path("teacher/class-learning-report", TeacherClassLearningReportView.as_view()),
    path("teacher/common-mistakes", TeacherCommonMistakesView.as_view()),
    path("teacher/high-risk-projects", TeacherHighRiskProjectsView.as_view()),
    path("teacher/intervention", TeacherInterventionCreateView.as_view()),
    path("teacher/rubrics", ScoringRubricListView.as_view()),
    path("teacher/case-library-summary", CaseLibrarySummaryView.as_view()),
    path("teacher/prompt-scenes", PromptSceneConfigListView.as_view()),
    path("teacher/common-issues", TeacherCommonIssuesView.as_view()),
    path("teacher/knowledge-recommendations", TeacherKnowledgeRecommendationView.as_view()),
    path("teacher/ai-chat", TeacherAIChatView.as_view()),
    path("teacher/students", TeacherStudentListView.as_view()),
    path("teacher/students/<int:student_id>/unbind", TeacherStudentUnbindView.as_view()),
    path("admin/overview", AdminOverviewView.as_view()),
    path("admin/users", AdminUserManageView.as_view()),
    path("admin/users/<int:user_id>/status", AdminUserStatusUpdateView.as_view()),
    path("admin/graphs/hypergraph", AdminHypergraphGraphView.as_view()),
    path("admin/graphs/knowledge", AdminKnowledgeGraphView.as_view()),
    path("admin/graphs/observability", AdminGraphObservabilityView.as_view()),
    path("project/<int:plan_id>/bottleneck", ProjectBottleneckView.as_view()),
    path("project/<int:plan_id>/rubric-score", ProjectRubricScoreDetailView.as_view()),
    path("project/<int:plan_id>/evidence-chain", ProjectEvidenceChainView.as_view()),
    path("project/<int:plan_id>/potential-report", ProjectPotentialReportView.as_view()),
    path("project/<int:plan_id>/hypergraph-reasoning", ProjectHypergraphReasoningView.as_view()),
    path("hypergraph/import-case", HypergraphImportCaseView.as_view()),
    path("hypergraph/preview-graph", HypergraphPreviewGraphView.as_view()),
]
